version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13.3
    working_directory: /go/src/github.com/anraku/circleci-sample
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go test -v ./...
